---
title: "classify-raster-data"
author: "Amy Hudson"
date: "June 21, 2016"
output: html_document
---

#Notes
require vs library
*library provides an error message
*require returns

```{r import-libraries}
#load libraries
library(raster)
library(rgdal)

```

#Import Canopy Height Model

```{r import-canopy-height}

chm <- raster("../NEONdata/D17-California/TEAK/2013/lidar/TEAK_lidarCHM.tif")
plot(chm,
    main = "this plots using the raster package")

image(chm,
      main = "these are just pixels and will stretch the space")
```

##Deal with 0 values

```{r assign-values-na}

hist(chm)
chm[chm==0]<- NA
hist(chm,
     xlab = "Tree height (m)")


```

##Import aspect data

```{r import-aspect}

aspect <- raster("../NEONdata/D17-California/TEAK/2013/lidar/TEAK_lidarAspect.tif")
plot(aspect)

```

##Create Classification Matrix

```{r class-matrix}
#North facing versus south facing , 
#Create a matrix
class.m <- c(0, 45, 1,
             45, 135, NA,
             135, 225, 2,
             225, 315, NA,
             315,360, 1)
rcl.m<- matrix(class.m,
               ncol=3,
               byrow=T)
rcl.m

```

##reclassify raster

```{r perform-reclass}

asp.ns <- reclassify(aspect,
                     rcl.m)
plot(asp.ns,
     main = "N and S Facing Slopes")

```

##Export Geotiff

```{r export-geotiff, eval=FALSE}
#take file, export to tiff file in outputs folder, 
writeRaster(asp.ns,
            file="../outputs/TEAK/Teak_nsAspect2.tif",
            options = "COMPRESS=LZW",
            NAflag = -9999)


```

## Mask Data

```{r raster-mask}

asp.ns #did we have to add this here? 

ndvi <- raster("../NEONdata/D17-California/TEAK/2013/spectrometer/veg_index/TEAK_NDVI.tif")

plot(ndvi,
     main = "NDVI for teakettle field site")

#mask data
nFacing.ndvi <- mask(ndvi,
                     asp.ns)
plot(nFacing.ndvi)
```

